# Generated by Django 6.0.3 on 2026-03-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisitedPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(help_text='Country name (e.g., Thailand, Japan)', max_length=100)),
                ('city', models.CharField(blank=True, help_text='City name (optional)', max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Latitude coordinate', max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Longitude coordinate', max_digits=9)),
                ('date_visited', models.DateField(help_text='When they visited (or start date of trip)')),
                ('photo', models.ImageField(help_text='Photo from this place', upload_to='travel_photos/')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about the visit')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Visited Place',
                'verbose_name_plural': 'Visited Places',
                'ordering': ['-date_visited'],
            },
        ),
    ]
