# Generated by Django 6.0.3 on 2026-04-03 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_planner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookedTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(help_text='Destination name (e.g., Japan, Thailand)', max_length=200)),
                ('start_date', models.DateField(help_text='Trip start date')),
                ('end_date', models.DateField(help_text='Trip end date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Booked Trip',
                'verbose_name_plural': 'Booked Trips',
                'ordering': ['-start_date'],
            },
        ),
    ]
