# Generated by Django 6.0.3 on 2026-04-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_planner', '0002_bookedtrip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Destination name', max_length=200, unique=True)),
                ('best_time', models.JSONField(default=dict)),
                ('travel_tips', models.JSONField(default=dict)),
                ('visa', models.JSONField(default=dict)),
                ('health', models.JSONField(default=dict)),
                ('must_sees', models.JSONField(default=dict)),
                ('food', models.JSONField(default=dict)),
                ('budget', models.JSONField(default=dict)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='destinations/')),
                ('is_dream_destination', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_dream_destination', 'name'],
            },
        ),
    ]
