# Generated by Django 6.0.3 on 2026-04-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_planner', '0003_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='image_filename',
            field=models.CharField(blank=True, help_text='Filename in static/images/', max_length=100),
        ),
    ]
