# Generated by Django 6.0.3 on 2026-04-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_planner', '0004_destination_image_filename'),
    ]

    operations = [
        migrations.CreateModel(
            name='WoodyChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(help_text='Destination being discussed', max_length=200)),
                ('role', models.CharField(help_text='user or assistant', max_length=20)),
                ('content', models.TextField(help_text='Message content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
