# Generated by Django 6.0.3 on 2026-04-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_planner', '0005_woodychat'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedtrip',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude for map', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='bookedtrip',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude for map', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='bookedtrip',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes about the trip'),
        ),
        migrations.AddField(
            model_name='bookedtrip',
            name='photo',
            field=models.ImageField(blank=True, help_text='Photo from the trip', null=True, upload_to='trip_photos/'),
        ),
    ]
