services:
  worker:
    build:
      context: ..
      dockerfile: workers/Dockerfile.worker
    command: python manage.py qcluster
    env_file:
      - ../.env
    environment:
      - DJANGO_SETTINGS_MODULE=bftravel.settings
    volumes:
      - ..:/app
    restart: unless-stopped
    stop_grace_period: 15s
    deploy:
      replicas: 3
